import { AppStateData, Country, UserProfile, Visa } from "@/lib/types";

export const defaultProfile: UserProfile = {
  fullName: "Taylor Demo",
  age: 31,
  residenceCountry: "United States",
  citizenships: ["United States"],
  maritalStatus: "single",
  educationLevel: "bachelor",
  employmentStatus: "employed",
  annualIncome: 52000,
  savingsAmount: 18000,
  languages: ["English", "Spanish"],
  englishLevel: "native",
  workExperienceYears: 7,
  hasCriminalRecord: false,
  canWorkRemotely: true,
  hasHealthInsurance: true,
  hasJobOffer: false,
  dependents: 0,
  familyMembers: 1,
};

export const countries: Country[] = [
  {
    code: "PT",
    name: "Portugal",
    flag: "🇵🇹",
    headline: "Atlantic lifestyle with a mature digital nomad path.",
    region: "Europe",
    costOfLivingBand: "$$",
    climate: "Mild coastal",
    heroColors: ["#8440F5", "#18C9DD"],
    highlights: ["Strong remote-worker demand", "Family-friendly", "Good rail access"],
  },
  {
    code: "ES",
    name: "Spain",
    flag: "🇪🇸",
    headline: "Fast-growing remote-work market with lifestyle appeal.",
    region: "Europe",
    costOfLivingBand: "$$",
    climate: "Warm Mediterranean",
    heroColors: ["#8F39F4", "#2F63F9"],
    highlights: ["Large expat hubs", "Remote tax interest", "High quality of life"],
  },
  {
    code: "EE",
    name: "Estonia",
    flag: "🇪🇪",
    headline: "Digital-first government and founder-friendly systems.",
    region: "Europe",
    costOfLivingBand: "$$",
    climate: "Cold winters",
    heroColors: ["#5460F1", "#20D2DE"],
    highlights: ["Digitized services", "Transparent processes", "Startup ecosystem"],
  },
  {
    code: "AE",
    name: "United Arab Emirates",
    flag: "🇦🇪",
    headline: "Premium remote work hub with a straightforward residence route.",
    region: "Middle East",
    costOfLivingBand: "$$$",
    climate: "Hot desert",
    heroColors: ["#6E46EF", "#19BDE0"],
    highlights: ["No income tax", "Large international community", "Fast processing"],
  },
  {
    code: "DE",
    name: "Germany",
    flag: "🇩🇪",
    headline: "Skilled migration route for candidates building a long-term base.",
    region: "Europe",
    costOfLivingBand: "$$$",
    climate: "Temperate seasons",
    heroColors: ["#5B51EC", "#2C6AE8"],
    highlights: ["Strong job market", "Path to residency", "Large economy"],
  },
  {
    code: "CR",
    name: "Costa Rica",
    flag: "🇨🇷",
    headline: "Lower-friction remote worker move with a lifestyle-first profile.",
    region: "Central America",
    costOfLivingBand: "$$",
    climate: "Tropical",
    heroColors: ["#9836F3", "#1FCFDF"],
    highlights: ["Warm climate", "Nature access", "Popular with remote workers"],
  },
];

export const visas: Visa[] = [
  {
    id: "pt-d8",
    name: "Portugal D8 Digital Nomad",
    countryCode: "PT",
    category: "Digital Nomad",
    summary: "Best for remote professionals with stable income and a clean record.",
    description:
      "Designed for remote earners who want a credible path into Portugal with room to expand later into family and longer-term residency options.",
    processingTime: "8-12 weeks",
    baseRequirements: [
      {
        id: "pt-remote",
        label: "Remote work eligibility",
        field: "canWorkRemotely",
        operator: "isTrue",
        detail: "Applicant needs provable remote or location-independent work.",
        premiumDetail: "Use this to surface employer letters or client contracts in the pathway.",
      },
      {
        id: "pt-income",
        label: "Income threshold",
        field: "annualIncome",
        operator: "gte",
        value: 36000,
        detail: "Annual income should meet the MVP threshold for qualification.",
        premiumDetail: "Show the equivalent monthly threshold and acceptable proof documents.",
      },
      {
        id: "pt-insurance",
        label: "Health coverage",
        field: "hasHealthInsurance",
        operator: "isTrue",
        detail: "Applicant should have valid health insurance for the move.",
      },
      {
        id: "pt-record",
        label: "Criminal record",
        field: "hasCriminalRecord",
        operator: "isFalse",
        detail: "The route assumes no criminal record issues.",
      },
    ],
    alternativeGroups: [],
    optionalBoosts: ["Portuguese tax planning guidance", "Lease prep checklist", "Dependents folder"],
    documents: [
      { id: "pt-doc-1", title: "Passport copy", description: "Photo page and remaining validity." },
      { id: "pt-doc-2", title: "Income evidence", description: "Payslips, contracts, or client statements." },
      { id: "pt-doc-3", title: "Health insurance proof", description: "Coverage certificate with effective dates." },
    ],
    steps: [
      { id: "pt-step-1", title: "Validate profile fit", description: "Check income, record, and remote work profile." },
      { id: "pt-step-2", title: "Gather income proof", description: "Collect the strongest evidence for recurring income." },
      { id: "pt-step-3", title: "Prepare application packet", description: "Combine forms, insurance, and travel documents.", premium: true },
      { id: "pt-step-4", title: "Track consular appointment", description: "Monitor appointment and follow-up timing.", premium: true },
    ],
    premiumInsights: [
      "Starter users can see basic qualification, but premium can surface why specific evidence is weak.",
      "Applicants with family members should front-load housing and insurance planning.",
    ],
    isActive: true,
  },
  {
    id: "es-digital-nomad",
    name: "Spain Digital Nomad Visa",
    countryCode: "ES",
    category: "Digital Nomad",
    summary: "For remote professionals who satisfy income and either experience or degree criteria.",
    description:
      "A strong fit for remote workers targeting Spain with a more premium upsell around documentation quality and pathway sequencing.",
    processingTime: "4-8 weeks",
    baseRequirements: [
      {
        id: "es-remote",
        label: "Remote work eligibility",
        field: "canWorkRemotely",
        operator: "isTrue",
        detail: "Applicant needs location-independent work with foreign income.",
      },
      {
        id: "es-income",
        label: "Income threshold",
        field: "annualIncome",
        operator: "gte",
        value: 32000,
        detail: "The profile should show enough annual income for the route.",
      },
      {
        id: "es-record",
        label: "Criminal record",
        field: "hasCriminalRecord",
        operator: "isFalse",
        detail: "The route assumes no criminal record problems.",
      },
    ],
    alternativeGroups: [
      {
        id: "es-path-experience",
        label: "Experience route",
        description: "Use work experience as the core proof path.",
        requirements: [
          {
            id: "es-exp-years",
            label: "Professional experience",
            field: "workExperienceYears",
            operator: "gte",
            value: 3,
            detail: "Three or more years of work experience is the MVP threshold.",
          },
        ],
      },
      {
        id: "es-path-education",
        label: "Education route",
        description: "Use education credentials as the alternative proof path.",
        requirements: [
          {
            id: "es-edu-level",
            label: "Education threshold",
            field: "educationLevel",
            operator: "atLeastEducation",
            value: "bachelor",
            detail: "Bachelor's degree or higher satisfies the MVP education route.",
          },
        ],
      },
    ],
    optionalBoosts: ["Spanish-speaking support", "Tax residency explainer", "Employer letter template"],
    documents: [
      { id: "es-doc-1", title: "Remote work contract", description: "Employer or client contract showing remote arrangement." },
      { id: "es-doc-2", title: "Income evidence", description: "Bank statements or payment history." },
      { id: "es-doc-3", title: "Experience or degree proof", description: "Resume, references, or diploma depending on route." },
    ],
    steps: [
      { id: "es-step-1", title: "Choose proof route", description: "Select either the experience or education evidence path." },
      { id: "es-step-2", title: "Compile earnings trail", description: "Prepare a clean story for recurring income." },
      { id: "es-step-3", title: "Assemble local readiness docs", description: "Insurance, translations, and appointment prep.", premium: true },
      { id: "es-step-4", title: "Respond to evidence gaps", description: "Track follow-up requests from the authority.", premium: true },
    ],
    premiumInsights: [
      "This is a good demo visa for conditional requirements because the path can be education or experience.",
      "Premium should explain which route is strongest for the user profile instead of only showing a pass/fail result.",
    ],
    isActive: true,
  },
  {
    id: "ee-digital-nomad",
    name: "Estonia Digital Nomad Visa",
    countryCode: "EE",
    category: "Digital Nomad",
    summary: "Great fit for remote workers with strong income and a digital-first preference.",
    description:
      "A clean candidate for the MVP because the qualification rules are straightforward and easy to explain in a checklist flow.",
    processingTime: "3-6 weeks",
    baseRequirements: [
      {
        id: "ee-remote",
        label: "Remote work eligibility",
        field: "canWorkRemotely",
        operator: "isTrue",
        detail: "The applicant should already be working remotely.",
      },
      {
        id: "ee-income",
        label: "Income threshold",
        field: "annualIncome",
        operator: "gte",
        value: 45000,
        detail: "The profile should show sufficiently strong earnings.",
      },
      {
        id: "ee-record",
        label: "Criminal record",
        field: "hasCriminalRecord",
        operator: "isFalse",
        detail: "The MVP rules assume no criminal record issues.",
      },
    ],
    alternativeGroups: [],
    optionalBoosts: ["E-residency explainer", "Cold-weather relocation checklist", "Contractor invoicing notes"],
    documents: [
      { id: "ee-doc-1", title: "Employment proof", description: "Letter, contracts, or company ownership documentation." },
      { id: "ee-doc-2", title: "Income statements", description: "Bank statements or payslips with stable history." },
      { id: "ee-doc-3", title: "Accommodation plan", description: "Reservation or housing confirmation for arrival." },
    ],
    steps: [
      { id: "ee-step-1", title: "Validate remote work evidence", description: "Choose the strongest proof source." },
      { id: "ee-step-2", title: "Prepare finance packet", description: "Show income stability and source of earnings." },
      { id: "ee-step-3", title: "Submit route-specific documents", description: "Handle the digital nomad evidence package.", premium: true },
    ],
    premiumInsights: [
      "This route is easy to match but benefits from premium explanations around proof quality.",
    ],
    isActive: true,
  },
  {
    id: "ae-virtual-work",
    name: "UAE Virtual Work Residence",
    countryCode: "AE",
    category: "Remote Work",
    summary: "Best for higher-income remote workers who want a fast relocation pathway.",
    description:
      "A premium-feeling route that works well in the MVP as a contrast to Europe-focused options and a stronger-income recommendation.",
    processingTime: "2-4 weeks",
    baseRequirements: [
      {
        id: "ae-remote",
        label: "Remote work eligibility",
        field: "canWorkRemotely",
        operator: "isTrue",
        detail: "The applicant should have fully remote work.",
      },
      {
        id: "ae-income",
        label: "Income threshold",
        field: "annualIncome",
        operator: "gte",
        value: 60000,
        detail: "The route is best for applicants above the premium threshold.",
      },
      {
        id: "ae-insurance",
        label: "Health coverage",
        field: "hasHealthInsurance",
        operator: "isTrue",
        detail: "Health insurance should be active before the move.",
      },
    ],
    alternativeGroups: [],
    optionalBoosts: ["Housing launch plan", "Cost-of-living warning", "Tax and payroll checklist"],
    documents: [
      { id: "ae-doc-1", title: "Employment verification", description: "Letter confirming remote status and compensation." },
      { id: "ae-doc-2", title: "Bank statements", description: "Recent statements supporting the income threshold." },
      { id: "ae-doc-3", title: "Health insurance certificate", description: "Valid coverage documentation." },
    ],
    steps: [
      { id: "ae-step-1", title: "Confirm premium-fit profile", description: "Make sure earnings and insurance are lined up." },
      { id: "ae-step-2", title: "Collect proof pack", description: "Gather employer and banking records." },
      { id: "ae-step-3", title: "Track approval and move planning", description: "Follow post-approval setup tasks.", premium: true },
    ],
    premiumInsights: [
      "This route is a strong upsell candidate because cost of living and supporting proof need more explanation.",
    ],
    isActive: true,
  },
  {
    id: "de-opportunity-card",
    name: "Germany Opportunity Card",
    countryCode: "DE",
    category: "Skilled Migration",
    summary: "For candidates with education or experience plus language readiness and savings.",
    description:
      "Useful for the MVP because it introduces a different user intent: not only remote workers, but people planning a longer-term skilled move.",
    processingTime: "6-10 weeks",
    baseRequirements: [
      {
        id: "de-savings",
        label: "Savings threshold",
        field: "savingsAmount",
        operator: "gte",
        value: 12000,
        detail: "Savings help support the early settlement period.",
      },
      {
        id: "de-language",
        label: "English proficiency",
        field: "englishLevel",
        operator: "atLeastLanguage",
        value: "conversational",
        detail: "The MVP assumes at least conversational English.",
      },
      {
        id: "de-record",
        label: "Criminal record",
        field: "hasCriminalRecord",
        operator: "isFalse",
        detail: "Applicants should not have a criminal record issue.",
      },
    ],
    alternativeGroups: [
      {
        id: "de-path-education",
        label: "Education route",
        description: "Qualify through recognized education.",
        requirements: [
          {
            id: "de-edu",
            label: "Education threshold",
            field: "educationLevel",
            operator: "atLeastEducation",
            value: "associate",
            detail: "Associate level or higher is used in the MVP data model.",
          },
        ],
      },
      {
        id: "de-path-experience",
        label: "Experience route",
        description: "Qualify through depth of experience.",
        requirements: [
          {
            id: "de-exp",
            label: "Professional experience",
            field: "workExperienceYears",
            operator: "gte",
            value: 5,
            detail: "Five or more years of experience can satisfy the route.",
          },
        ],
      },
    ],
    optionalBoosts: ["German-language prep", "Job-market overview", "Recognition dossier"],
    documents: [
      { id: "de-doc-1", title: "Proof of savings", description: "Statements showing the support threshold." },
      { id: "de-doc-2", title: "Language evidence", description: "Test results or equivalent proficiency evidence." },
      { id: "de-doc-3", title: "Education or experience proof", description: "Diploma, work history, and references." },
    ],
    steps: [
      { id: "de-step-1", title: "Pick the strongest qualification route", description: "Choose education or experience." },
      { id: "de-step-2", title: "Build the readiness packet", description: "Savings, language, and qualification evidence." },
      { id: "de-step-3", title: "Plan arrival and job search", description: "Prepare the first-month onboarding tasks.", premium: true },
    ],
    premiumInsights: [
      "The route is ideal for showing 'fix this to qualify' because the app can suggest concrete gaps like savings or language prep.",
    ],
    isActive: true,
  },
  {
    id: "cr-digital-nomad",
    name: "Costa Rica Digital Nomad",
    countryCode: "CR",
    category: "Digital Nomad",
    summary: "Lifestyle-driven route with simpler requirements for remote workers.",
    description:
      "This option rounds out the MVP by giving the user a lower-friction, non-European recommendation when income is solid but not premium-tier high.",
    processingTime: "3-5 weeks",
    baseRequirements: [
      {
        id: "cr-remote",
        label: "Remote work eligibility",
        field: "canWorkRemotely",
        operator: "isTrue",
        detail: "The move assumes the applicant already works remotely.",
      },
      {
        id: "cr-income",
        label: "Income threshold",
        field: "annualIncome",
        operator: "gte",
        value: 30000,
        detail: "Annual income should meet the MVP threshold for the route.",
      },
      {
        id: "cr-insurance",
        label: "Health coverage",
        field: "hasHealthInsurance",
        operator: "isTrue",
        detail: "Insurance should be in place before travel.",
      },
    ],
    alternativeGroups: [],
    optionalBoosts: ["Family move overview", "Schooling research", "Arrival checklist"],
    documents: [
      { id: "cr-doc-1", title: "Proof of remote income", description: "Income and client/employer documentation." },
      { id: "cr-doc-2", title: "Insurance proof", description: "Coverage for the planned stay." },
      { id: "cr-doc-3", title: "Passport package", description: "Identity documentation and validity proof." },
    ],
    steps: [
      { id: "cr-step-1", title: "Confirm remote income", description: "Validate remote-work proof and monthly history." },
      { id: "cr-step-2", title: "Prepare travel-ready documents", description: "Identity, insurance, and supporting docs." },
      { id: "cr-step-3", title: "Track post-arrival tasks", description: "Manage follow-up setup after approval.", premium: true },
    ],
    premiumInsights: [
      "This route is a good free-to-premium conversion lever because the base qualification is easy but the move logistics are not.",
    ],
    isActive: true,
  },
];

export const initialState: AppStateData = {
  profile: defaultProfile,
  tier: "starter",
  pathways: [
    {
      id: "starter-pathway-1",
      visaId: "pt-d8",
      startedAt: "2026-03-24T14:00:00.000Z",
      completedStepIds: ["pt-step-1"],
      completedDocumentIds: ["pt-doc-1"],
    },
  ],
  notifications: [
    {
      id: "notif-1",
      title: "Portugal pathway started",
      message: "Your Portugal D8 pathway is active. Next up: gather income proof.",
      createdAt: "2026-03-29T15:30:00.000Z",
      read: false,
      kind: "pathway",
      visaId: "pt-d8",
    },
    {
      id: "notif-2",
      title: "Premium insight available",
      message: "Spain and Germany each have a stronger path explanation waiting behind premium.",
      createdAt: "2026-03-28T13:15:00.000Z",
      read: false,
      kind: "eligibility",
    },
  ],
  countries,
  visas,
};
